FROM python:3.9-slim

RUN apt-get update && \
    apt-get install -y default-jre-headless && \
    apt-get clean;

WORKDIR /app

RUN pip install --no-cache-dir pyspark==3.5.0 pandas>=2.2.0 scikit-learn>=1.4.0 psycopg2-binary

COPY ./src /app/src

CMD ["python", "src/streaming/spark_processor.py"]